// src/web/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';
import { Observable, Subject, filter, first, map } from 'rxjs';
import { StackService } from '../../lib/api';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, HttpClientModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  private count = new Subject<number>();

  title = 'web';

  count$ = this.count.asObservable();

  openApiDocs$: Observable<string>;

  constructor(private stackService: StackService) {
    this.openApiDocs$ = this.stackService
      .health()
      .pipe(map((health) => health.hrefs.openApiDocs));
  }

  ngOnInit(): void {
    this.stackService
      .getCount()
      .pipe(
        first(),
        filter((count) => !!count),
        map((count) => {
          this.count.next(count.count);
        }),
      )
      .subscribe();
  }

  increment(): void {
    this.stackService
      .incrementCount()
      .pipe(map((count) => this.count.next(count.count)))
      .subscribe();
  }
}

<div>
  <a href="https://serverless.com" target="_blank" rel="noreferrer">
    <img src="assets/serverless.svg" class="logo" alt="Serverless logo" />
  </a>
  <a href="https://expressjs.com" target="_blank" rel="noreferrer">
    <img src="assets/expressjs.svg" class="logo" alt="ExpressJS logo" />
  </a>
  <a href="https://angular.io" target="_blank" rel="noreferrer">
    <img src="assets/angular.svg" class="logo" alt="Angular logo" />
  </a>
</div>
<h1>Serverless + Express + Angular</h1>
<h4>powered with</h4>
<h2>
  <strong>
    GitHub Codespaces + Localstack + AWS Lambda + DynamoDB + OpenAPI
  </strong>
</h2>
<h5>supercharged by</h5>
<h3>
  <strong>
    Websockets + DynamoDB Events + SQS Queues + SNS Topics + S3 Events
  </strong>
</h3>
<div>
  <a href="https://scaffoldly.dev" target="_blank" rel="noreferrer">
    <img src="assets/scaffoldly-built.svg" class="built-with" alt="Built with Scaffoldly" />
  </a>
</div>
<div class="card">
  <button type="button" (click)="increment()">
    count is {{ count$ | async }}
  </button>
  <p>
    Edit <code>src/api/index.ts</code> and save to modify the Express API
  </p>
  <p>
    Edit <code>src/web/app/app.component.html</code> and save to modify the Angular
    Frontend
  </p>
  <p>
    Open <a *ngIf="openApiDocs$ | async as openApiDocs; else loading" [href]="openApiDocs" target="_blank"
      rel="noreferrer">
      Swagger
    </a><ng-template #loading>
      <code>Loading...</code>
    </ng-template> to see OpenAPI Docs for this project
  </p>
</div>

// src/web/App.tsx
import React, { useEffect, useState } from 'react';
import serverlessLogo from '../../public/serverless.svg';
import reactLogo from './assets/react.svg';
import expressjsLogo from '../../public/expressjs.svg';
import scaffoldlyBuilt from '../../public/scaffoldly-built.svg';
import './App.css';
import { health, incrementCount, getCount } from '../lib/api';

function App(): React.JSX.Element {
  const [count, setCount] = useState(0);
  const [openApiDocs, setOpenApiDocs] = useState<string>();

  useEffect(() => {
    health().then((response) =>
      setOpenApiDocs(response.data.hrefs.openApiDocs),
    );
    getCount().then((response) => setCount(response.data.count || 0));
  }, []);

  const increment = (): void => {
    incrementCount().then((response) => setCount(response.data.count));
  };

  return (
    <>
      <div>
        <a href="https://serverless.com" target="_blank" rel="noreferrer">
          <img src={serverlessLogo} className="logo" alt="Serverless logo" />
        </a>
        <a href="https://expressjs.com" target="_blank" rel="noreferrer">
          <img src={expressjsLogo} className="logo" alt="ExpressJS logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo" alt="React logo" />
        </a>
      </div>
      <h1>Serverless + Express + React</h1>
      <h4>powered by</h4>
      <h2>
        <strong>
          GitHub Codespaces + Localstack + AWS Lambda + DynamoDB + OpenAPI
        </strong>
      </h2>
      <h5>supercharged with</h5>
      <h3>
        <strong>
          Websockets + DynamoDB Events + SQS Queues + SNS Topics + S3 Events
        </strong>
      </h3>
      <div>
        <a href="https://scaffoldly.dev" target="_blank" rel="noreferrer">
          <img
            src={scaffoldlyBuilt}
            className="built-with"
            alt="Built with Scaffoldly"
          />
        </a>
      </div>
      <div className="card">
        <button type="button" onClick={() => increment()}>
          count is {count}
        </button>
        <p>
          Edit <code>src/api/index.ts</code> and save to modify ESBuild+Express
          API
        </p>
        <p>
          Edit <code>src/web/App.tsx</code> and save to modify Vite+React
          Frontend
        </p>
        <p>
          Open{' '}
          {openApiDocs ? (
            <a href={openApiDocs} target="_blank" rel="noreferrer">
              Swagger
            </a>
          ) : (
            <code>Loading...</code>
          )}{' '}
          to see OpenAPI Docs for this project
        </p>
      </div>
    </>
  );
}

export default App;
